name: Deploy your website to gh_pages branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # "At minute 0 . every hour"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Berlin"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python V. 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install meetlify

      - name: Run Custom tasks 
        run: |
          # meetlify clean
          # meetlify setup
          meetlify make
      
      - name: Prettify code
        run: |
          sudo apt install tidy
          find ./output -name '*.html' -type f -print -exec tidy -mq '{}' \;

      - name: Deploy Website/Documents
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
